---
title: "LOGISTIC REGRESSION"
format: html
editor: visual
df-print: kable
code-overflow: wrap
execute: 
  echo: true
  warning: false
  message: false
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(gtsummary)
library(gt) 
library(finalfit)
library(broom)
library(patchwork)
theme_set(theme_bw())


```

### Check the data
```{r}
melanoma <- boot::melanoma
melanoma %>% glimpse()
melanoma %>% ff_glimpse()

```
### Recode the data
```{r}
melanoma <- melanoma %>% 
  mutate(sex.factor= factor(sex) %>% 
           fct_recode("Female" = "0",
                      "Male"= "1") %>% 
           ff_label("Sex"),
         
         ulcer.factor = factor(ulcer) %>% 
           fct_recode("Present"= "1",
                      "Absent"= "0") %>% 
           ff_label("Ulcerated tumour"),
         
         age =ff_label(age,"Age (years)"),
         year = ff_label(year, "Year"),
         
         status.factor=factor(status) %>% 
           fct_recode("Died melanoma" = "1",
                      "Alive" = "2",
                      "Died-other" = "3") %>% 
           fct_relevel("Alive") %>% 
           ff_label("Status"),
         
           t_stage.factor = thickness %>% 
           cut(breaks = c(0,1.0,2.0,4.0,max(thickness,na.rm = TRUE)),
               include.lowest = TRUE) %>% 
            fct_recode(
             "T1" = "[0,1]",
             "T2" = "(1,2]",
             "T3" = "(2,4]",
             "T4" = "(4,17.4]") %>% 
  ff_label("T-stage")
           
         )



```



```{r}
melanoma %>% 
  ggplot(aes(x = time))+
  geom_histogram()+
  facet_grid(.~status.factor)
```

```{r}
melanoma <- melanoma %>% 
  mutate(mort_5yr = 
           if_else((time/365)< 5 & (status ==1),
                   "Yes","No") %>% 
           fct_relevel("No") %>% 
           ff_label("5-year survival"))
```


```{r}
p1 <- melanoma %>% 
  ggplot(aes(x = ulcer.factor, fill = mort_5yr))+
  geom_bar()+
  theme(legend.position = "none")+
  scale_fill_viridis_d( option = "viridis")

p2 <- melanoma %>% 
  ggplot(aes(x = ulcer.factor, fill = mort_5yr))+
  geom_bar(position = "fill")+
  ylab("proportion")+
  scale_fill_viridis_d( option = "viridis")

p1+p2
```

### Tabulate Data
```{r}
dependent <- "ulcer.factor"
explanatory <- c("age","sex.factor","year","t_stage.factor")

melanoma %>% 
  summary_factorlist(dependent,explanatory, p = TRUE,add_dependent_label = TRUE)
```




```{r}
melanoma %>% 
  select(age,sex.factor,year,t_stage.factor,ulcer.factor) %>% 
  tbl_summary(
    by = ulcer.factor,
    statistic = 
      list(all_categorical() ~ "{n} ({p}%)",
           all_continuous() ~ "{mean} ({sd})"),
     digits = list(all_categorical() ~ 0,
                  all_continuous() ~ 0),
  ) %>% 
  add_overall() %>% 
  bold_labels() %>% 
  italicize_levels() %>% 
  modify_spanning_header(update = all_stat_cols() ~ "**Tumour Ulceration**")
```


```{r}
melanoma %>% 
  mutate(
    mort_5yr_num = as.numeric(mort_5yr)-1
  ) %>% 
  select(mort_5yr_num,age,year) %>% 
  pivot_longer(all_of(c("age","year")), names_to = "predictors") %>% 
  ggplot(aes(x = value, y= mort_5yr_num))+
  geom_point(size = 0.5, alpha = 0.5)+
  geom_smooth(method = "loess")+
  facet_wrap(~predictors , scales = "free_x")


```


```{r}
select_explanatory <- c("age","ulcer.factor","sex.factor","t_stage.factor")
melanoma %>% 
  select(all_of(select_explanatory)) %>% 
  pivot_longer(-age) %>% 
  ggplot(aes(value,age))+
  geom_boxplot()+
  facet_wrap(~ name, scale= "free", ncol = 3)+
  coord_flip()

```


```{r}
select_explanatory <- c("ulcer.factor","sex.factor","t_stage.factor")
melanoma %>% 
  select(one_of(select_explanatory)) %>% 
  pivot_longer(-sex.factor) %>% 
  ggplot(aes(value,fill = sex.factor))+
  geom_bar(position = "fill")+
  ylab("Proportion")+
  facet_wrap(~name, scale = "free", ncol = 2)+
  coord_flip()

```

### Variance Inflation Factor
```{r}
dependent <- "mort_5yr"
explanatory <- c("ulcer.factor","age","sex.factor","year","t_stage.factor")

melanoma %>% 
  glmmulti(dependent,explanatory) %>% 
  car::vif()


```


### Fitting Logistic Regression Models In Base R
```{r}
slr1 <- melanoma %>% 
  glm(mort_5yr ~ ulcer.factor, family = binomial(), data = .)
summary(slr1)

coef(slr1) %>% exp()

confint(slr1) %>% exp()

```


```{r}
slr1 %>% 
  tidy(conf.int = TRUE, exponentiate = TRUE)

slr1 %>% glance()

```

### Fitting logistic regression models with finalfit
```{r}
dependent <- "mort_5yr"
explanatory <- "ulcer.factor"
slr2 <- melanoma %>% 
  finalfit(dependent,explanatory, metrics = TRUE)
 


knitr::kable(slr2[[1]], row.names=FALSE, align=c("l", "l", "r", "r", "r", "r"))
knitr::kable(slr2[[2]], row.names=FALSE, col.names="")


```


```{r}
dependent <- "mort_5yr"
explanatory <- c("ulcer.factor","age","sex.factor","t_stage.factor")

slr3  <- melanoma %>% 
  finalfit(dependent,explanatory, metrics = TRUE)
 


knitr::kable(slr3[[1]], row.names=FALSE, align=c("l", "l", "r", "r", "r", "r"))
knitr::kable(slr3[[2]], row.names=FALSE, col.names="")


```



```{r}
melanoma <- melanoma %>% 
  mutate(age.factor = cut(age,breaks = c(0,25,50,75,100)) %>% 
           ff_label("Age (years)"))

slr4 <-  melanoma %>% 
  finalfit(dependent,c("ulcer.factor","age.factor"), metrics = TRUE)


knitr::kable(slr4[[1]], row.names=FALSE, align=c("l", "l", "r", "r", "r", "r"))
knitr::kable(slr4[[2]], row.names=FALSE, col.names="")
```


```{r}
## Adding a quadratic term to age
melanoma %>% 
  glm(mort_5yr ~ ulcer.factor + I(age^2) + age, family = binomial, data =.) %>% 
  tidy()

dependent <- "mort_5yr"
explanatory <- c("ulcer.factor","I(age^2)","age")
slr5 <- melanoma %>% 
  finalfit(dependent,explanatory,metrics = TRUE)

knitr::kable(slr5[[1]], row.names=FALSE, align=c("l", "l", "r", "r", "r", "r"))
knitr::kable(slr5[[2]], row.names=FALSE, col.names="")


```


```{r}
## visualizing the contribution of a particular variable by removing it from the model
# Removing age
dependent <- "mort_5yr"
explanatory <- c("ulcer.factor","age.factor","sex.factor","t_stage.factor")
explanatory_multi <- c("ulcer.factor","sex.factor","t_stage.factor")

slr6 <- melanoma %>% 
  finalfit(dependent,explanatory,explanatory_multi, keep_models = TRUE, metrics = TRUE)

knitr::kable(slr6[[1]], row.names=FALSE, align=c("l", "l", "r", "r", "r", "r","r"))
knitr::kable(slr6[[2]], row.names=FALSE, col.names="")

```

```{r}
## Removing Sex
dependent <- "mort_5yr"
explanatory <- c("ulcer.factor","sex.factor","t_stage.factor")
explanatory_multi <- c("ulcer.factor","t_stage.factor")

slr7 <- melanoma %>% 
  finalfit(dependent,explanatory,explanatory_multi, keep_models = TRUE, metrics = TRUE)

knitr::kable(slr7[[1]], row.names=FALSE, align=c("l", "l", "r", "r", "r", "r","r"))
knitr::kable(slr7[[2]], row.names=FALSE, col.names="")
```


```{r}
## checking for interaction between tumour stage and ulceration
dependent <- "mort_5yr"
explanatory <- c("ulcer.factor","t_stage.factor")
explanatory_multi <- c("ulcer.factor * t_stage.factor")

slr8 <- melanoma %>%
  ff_interaction(ulcer.factor,t_stage.factor) %>% 
  finalfit(dependent,explanatory,explanatory_multi, keep_models = TRUE, metrics = TRUE)






knitr::kable(slr8[[1]],row.names=FALSE,  align=c("l", "l", "r", "r", "r", "r","r"))
knitr::kable(slr8[[2]],row.names=FALSE,  col.names="")


```



```{r}
dependent <- "mort_5yr"
explanatory <- c("ulcer.factor","age.factor","sex.factor","t_stage.factor")
explanatory_multi <- c("ulcer.factor","t_stage.factor")

slr9 <- melanoma %>% 
  finalfit(dependent,explanatory,explanatory_multi, keep_models = TRUE, metrics = TRUE)

knitr::kable(slr9[[1]], row.names=FALSE, align=c("l", "l", "r", "r", "r", "r","r"))
knitr::kable(slr9[[2]], row.names=FALSE, col.names="")
```



### Odds Ratio Plot
```{r}
dependent <- "mort_5yr"
explanatory_multi <- c("ulcer.factor","t_stage.factor")

melanoma %>% 
  or_plot(dependent,explanatory_multi,
          breaks = c(0.5,1,2,5,10,25),
          table_text_size = 3.5,
          title_text_size = 16)
```


###Mixed Effect Models

#### Simulate Data

```{r}
## simulate random hospital identifier
set.seed(1)
melanoma <- melanoma %>% 
  mutate(hospital_id = sample(1:4,205,replace = TRUE))
melanoma <- melanoma %>% 
  mutate(hospital_id = c(rep(1:3,50), rep(4,55))) %>% 
  relocate(hospital_id,.before = time)
```


### Plot The Data
```{r}

melanoma %>% 
mutate(mort_5yr.num = as.numeric(mort_5yr)-1) %>%  # convert factor to 0 & 1  
 ggplot(aes(x = as.numeric(t_stage.factor), y = mort_5yr.num)) +
  geom_jitter(width = 0.1, height = 0.1)+
  geom_smooth(method = "loess", se = FALSE)+
  facet_wrap(~ hospital_id)+
  labs( x = "T-stage", y = "Mortality(5 y)")
         
```


```{r}
## fitting mixed effects model
# random intercept model
library(lme4)
lmem1 <- melanoma %>% 
  glmer(mort_5yr ~ t_stage.factor + (1| hospital_id), family = "binomial",data=.) 
summary(lmem1)


```



```{r}
dependent <- "mort_5yr"
explanatory <- "t_stage.factor"
random_effect <- "hospital_id"
random_effect <- "(1| hospital_id)"
lmem2 <- melanoma %>% 
  finalfit(dependent,explanatory,
           random_effect =random_effect,
           metrics = TRUE)

knitr::kable(lmem2[[1]], row.names=FALSE, align=c("l", "l", "r", "r", "r", "r","r"))
knitr::kable(lmem2[[2]], row.names=FALSE, col.names="")
```



```{r}
dependent <- "mort_5yr"
explanatory <- c("ulcer.factor","age.factor","sex.factor","t_stage.factor")
explanatory_multi <- c("ulcer.factor","t_stage.factor")
random_effect <- "hospital_id"

lme3 <- melanoma %>% 
  finalfit(dependent,explanatory,explanatory_multi, random_effect,
           keep_models = TRUE, metrics = TRUE)

knitr::kable(lme3[[1]], row.names=FALSE, align=c("l", "l", "r", "r", "r", "r","r","r"))
knitr::kable(lme3[[2]], row.names=FALSE, col.names="")
```












































































