---
title: "PROJECT WORK TABLE 1"
author: "K.ASABERE"
format: html
code-line-numbers: true
editor: visual
execute: 
  echo: true
  warning: false
  message: false
editor_options: 
  chunk_output_type: console
---

## 

```{r}
library(tidyverse)
library(gtsummary)
library(gt)
```



```{r}
heart_failure <- read_csv("heart_failure_clinical_records_dataset.csv")

glimpse(heart_failure)

spec(heart_failure)
```

#  Recoding variables 

```{r}
heart_recoded <-  heart_failure %>% 
  mutate(`Age(years)` = if_else(age <65,"less than 65","65 and above"),
  Anaemia=if_else(anaemia == 1,"Yes","No"),
 Sex = if_else(sex == 1,"Male","Female"),
`Serum creatinine(mg/dl)` = if_else(serum_creatinine >=1.5,"Elevated","Normal"),
Diabetes = if_else(diabetes == 1,"Yes","No"),
Smoking = if_else(smoking ==1, "Yes","No"),
Hypertension = if_else(high_blood_pressure ==1,"Yes","No"),
 `Ejection Fraction` = if_else(ejection_fraction <= 30,"HFrEF",
if_else(ejection_fraction <=45,"HFmrEF","HFpEF")),
`Serum sodium(mEq/L)`= serum_sodium,
Platelets = platelets,
`Time(days)` = time,
`Creatinine phosphokinase(mcg/dL)`=creatinine_phosphokinase
)


heart_df <- heart_recoded %>% 
 select(`Age(years)`:`Creatinine phosphokinase(mcg/dL)`)


heart_df <- heart_df %>%
  mutate(`Ejection Fraction` = factor(`Ejection Fraction`, levels = c("HFrEF", "HFmrEF", "HFpEF"),
labels= c("Reduced ejection fraction(HFrEF)", "Moderate ejection fraction(HFmrEF)",
    "Preserved ejection fraction(HFpEF)"))) %>% 
  relocate(Anaemia,.before = Diabetes)


head(heart_df)
glimpse(heart_df)
str(heart_df)
                                  
```




## A Function to create multiple bar plots for the categorical variables

# Colourful plots with Viridis palette
```{r}
Bargraph <- function(var){
  heart_df %>% 
    ggplot(aes( x= {{var}}))+
    geom_bar(aes(fill = {{var}}))+
    theme_bw()+
    theme(legend.position = "none")+
    scale_fill_viridis_d(option = "viridis")
}

heart_df %>% select(`Age(years)`:`Ejection Fraction`) %>% 
  map(Bargraph)

```

```{r}
Densityplots <- function(var){
  heart_df %>% 
    ggplot(aes( x={{var}}))+
    geom_density(fill = "steelblue",alpha = 0.5)+
    theme_bw()+
    theme(legend.position = "none")
    
}

heart_df %>% select(`Serum sodium(mEq/L)`:`Creatinine phosphokinase(mcg/dL)`) %>% 
  map(Densityplots)
```

## Boxplots for continuos variables vs Ejection fraction
```{r}
Boxplot <- function(var){
  heart_df %>% 
    ggplot(aes( x= `Ejection Fraction`,y={{var}}))+
    geom_boxplot(aes(fill= `Ejection Fraction`))+
    theme_bw()+
    theme(legend.position = "none")+
    scale_fill_viridis_d(option = "viridis")
    
}

heart_df %>% select(`Serum sodium(mEq/L)`:`Creatinine phosphokinase(mcg/dL)`) %>% 
  map(Boxplot)

```


```{r}
Boxplot <- function(var){
  heart_df %>% 
    ggplot(aes( x= `Ejection Fraction`,y={{var}}))+
    geom_boxplot(aes(fill= `Ejection Fraction`))+
    theme_bw()+
    theme(legend.position = "none")+
    scale_fill_viridis_d(option = "viridis")
    
}

heart_df %>% select(`Serum sodium(mEq/L)`:`Creatinine phosphokinase(mcg/dL)`) %>% 
  map(Boxplot)

```

#Table 1

```{r}
 table_one <- heart_df %>% 
  tbl_summary(
    by = `Ejection Fraction`,
    type = c(`Serum sodium(mEq/L)`:`Creatinine phosphokinase(mcg/dL)`) ~ "continuous",
    statistic = all_continuous() ~ "{mean} ({sd})",
    digits = all_continuous() ~ 1
  ) 


table_one %>% 
  add_overall() %>% 
  bold_labels() %>% 
  italicize_levels() %>% 
  modify_spanning_header(
    update = all_stat_cols() ~ "**Classification of Heart Failure According to Ejection Fraction**"
  ) %>% 
  modify_footnote(
    update = all_stat_cols() ~
      "mean(sd) for continuous ;n(%) for categorical"
  ) 
  

  
```



`