---
title: "TABLES WITH THE GT PACKAGE"
author: "K.Asabere"
format: html
editor: visual
execute: 
  echo: true
  warning: false
  message: false
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(modeldata)
library(gt)
```

```{r}

scat_table1 <- scat %>% 
  select(Species,
         Length,
         Diameter,
         Mass,
         d13C,
         d15N) %>% 
  group_by(Species) %>% 
  summarise(across(where(is.numeric),
                 ~round(mean(.x,na.rm = TRUE),
                        1)),
            count = n())
 
```

## A Great Table
```{r}
scat_table1 %>% 
  gt( rowname_col = "Species") %>% 
  cols_label(count ~ "Count") %>% 
  tab_header(title = "California Poopie",
             subtitle = "Morphometric Data on Scat") %>% 
  tab_source_note(md("**Source**: Reid, R. E. B. (2015).
  A morphometric modeling approach to distinguishing among bobcat,
  coyote and gray fox scats. *Wildlife Biology*, 21(5), 254-262")) %>% 
  tab_spanner(label = "Physical Averages",
              columns = Length:Mass) %>% 
  tab_stubhead( label = "Species")
  
             
```


## A Stylized Version
```{r}

scat_table1 %>% 
  gt() %>% 
  cols_label(count ~ "Count") %>% 
  tab_header(title = "California Poopie",
             subtitle = "Morphometric Data on Scat") %>% 
  tab_source_note(md("**Source**: Reid, R. E. B. (2015). 
 A morphometric modeling approach to distinguishing among bobcat,
 coyote and gray fox scats. *Wildlife Biology*, 21(5), 254-262")) %>% 
  tab_spanner(label = "Physical Averages",
              columns = Length:Mass) %>% 
  opt_stylize(style = 2,color = "cyan")
  


```


```{r}
scat_table2 <- scat %>% 
  select(Species,
         Location,
         Site,
         Length,
         Diameter,
         Mass,
         d13C,
         d15N) %>% 
   group_by(Species,Site) %>% 
  summarise(across(where(is.numeric),
                 ~round(mean(.x,na.rm = TRUE),
                        1)),
            Count = n())

```

# Grouped Data
```{r}
scat_table2 %>% 
  ungroup() %>% 
  gt(groupname_col = "Species")
```



























